version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/linux.Dockerfile
    ports:
      - "8501:8501"
    networks:
      eurygaster_subnet:
        ipv4_address: ${IP}
    volumes:
      - eurygaster_volume:/app/uploads
volumes:
  eurygaster_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MOUNTING_VOLUME}
networks:
  eurygaster_subnet:
    driver: bridge
    ipam:
     config:
       - subnet: ${SUBNET}/${MASK}
         gateway: ${GATEWAY}
