# prometheus.yml

global:
  scrape_interval:     10s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
- job_name: eurygaster-svc
  honor_labels: true
  static_configs:
  - targets:
    - eurygaster-svc:3000  # metrics from Eurygaster service
