{
 "title": "eurygaster-deploy-dev",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "average_requests_per_sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(bentoml_api_server_request_total{service_name=\"eurygaster\", endpoint=\"/classify_image\"}[1m])"
    },
    {
     "expr": "rate(bentoml_api_server_request_total{service_name=\"eurygaster\", endpoint=\"/classify_eurygaster\"}[1m])"
    }
   ]
  },
  {
   "title": "requests_in_progress",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bentoml_api_server_request_in_progress{service_name=\"eurygaster\", endpoint=\"/classify_eurygaster\"}",
     "legendFormat": "/classify_eurygaster"
    },
    {
     "expr": "bentoml_api_server_request_in_progress{service_name=\"eurygaster\", endpoint=\"/classify_image\"}",
     "legendFormat": "/classify_image"
    }
   ]
  },
  {
   "title": "runner_in_progress",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bentoml_runner_request_in_progress{service_name=\"eurygaster\", endpoint=\"/run\", runner_name=\"eurygaster_binary_calib_dyn\"}",
     "legendFormat": "Image filter"
    },
    {
     "expr": "bentoml_runner_request_in_progress{service_name=\"eurygaster\", endpoint=\"/run\", runner_name=\"eurygaster_multiclass_calib_dyn\"}",
     "legendFormat": "Eurygaster classifier"
    }
   ]
  },
  {
   "title": "median_adaptive_batch",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(bentoml_runner_adaptive_batch_size_bucket{service_name=\"eurygaster\", runner_name=\"eurygaster_binary_calib_dyn\"}[1m]))",
     "legendFormat": "Image filter"
    },
    {
     "expr": "histogram_quantile(0.5, rate(bentoml_runner_adaptive_batch_size_bucket{service_name=\"eurygaster\", runner_name=\"eurygaster_multiclass_calib_dyn\"}[1m]))",
     "legendFormat": "Eurygaster classifier"
    }
   ]
  },
  {
   "title": "average_requests_duration, sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(bentoml_api_server_request_duration_seconds_bucket{service_name=\"eurygaster\", endpoint=\"/classify_image\"}[1m]))",
     "legendFormat": "Image filter"
    },
    {
     "expr": "histogram_quantile(0.99, rate(bentoml_api_server_request_duration_seconds_bucket{service_name=\"eurygaster\", endpoint=\"/classify_eurygaster\"}[1m]))",
     "legendFormat": "Eurygaster classifier"
    },
    {
     "expr": "histogram_quantile(0.99, rate(bentoml_api_server_request_duration_seconds_bucket{service_name=\"eurygaster\", endpoint=\"/metadata\"}[1m]))",
     "legendFormat": "Metadata"
    }
   ]
  }
 ]
}