version: '3.9'

networks:
  eurygaster:
    external: true

volumes:
  minio:

services:
  minio:
    image: minio/minio:${MINIO_TAG}
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio:/data
    restart: always
    networks:
      - eurygaster
