
networks:
  eurygaster:
    external: true

volumes:
  minio:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=${MINIO_VOLUME_SIZE},uid=1000

services:
  minio:
    image: minio/minio:${MINIO_TAG}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio:/data
    restart: always
    networks:
      - eurygaster
    deploy:
      resources:
        limits:
          cpus: ${MINIO_CPUS:-1}
          memory: ${MINIO_MEM:-4096M}
