
networks:
  keycloak:
    name: keycloak
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}/${MASK}
          gateway: ${GATEWAY}

volumes:
  pg-keycloak:

services:
  keycloak:
#    image: quay.io/keycloak/keycloak:${KEYCLOAK_TAG}
    image: playaru/keycloak-russian:${KEYCLOAK_TAG}
    container_name: keycloak-identity
    command: >
      start --hostname-strict=false --proxy-headers=forwarded|xforwarded --proxy passthrough
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: ${PG_USER}
      KC_DB_PASSWORD: ${PG_PASSWORD}
      KC_DB_URL_DATABASE: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KC_HOSTNAME_STRICT: "false"
      KC_HTTPS_CERTIFICATE_FILE: ${KC_HTTPS_CERTIFICATE_FILE}
      KC_HTTPS_CERTIFICATE_KEY_FILE: ${KC_HTTPS_CERTIFICATE_KEY_FILE}
      KC_HTTPS_PORT: ${HTTPS_PORT}
      KC_HTTPS_PROTOCOLS: TLSv1.3,TLSv1.2
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_PORT: ${HTTP_PORT}
      KC_LOGLEVEL: DEBUG
      KEYCLOAK_LOGLEVEL: DEBUG
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
#      KEYCLOAK_FRONTEND_URL: "https://eurygaster.ru/auth"
    volumes:
      - ./server.crt.pem:/opt/keycloak/conf/server.crt.pem
      - ./server.key.pem:/opt/keycloak/conf/server.key.pem
    ports:
      - "${HTTPS_PORT}:${HTTPS_PORT}"
#      - "${HTTP_PORT}:${HTTP_PORT}"
    expose:
      - "${HTTP_PORT}"
      - "${HTTPS_PORT}"
    networks:
      keycloak:
          ipv4_address: ${KEYCLOAK_IPV4}
    restart: always
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: ${KEYCLOAK_CPUS:-1}
          memory: ${KEYCLOAK_MEM:-4096M}

  postgres:
    image: postgres:${PG_TAG}
    container_name: keycloak-db
    command: >
      -c ssl=on
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg-keycloak:/var/lib/postgresql/data
    networks:
      keycloak:
        ipv4_address: ${PG_IPV4}
    restart: always
    deploy:
      resources:
        limits:
          cpus: ${PG_CPUS:-1}
          memory: ${PG_MEM:-4096M}
