version: "3.9"
x-environment:
  &default-environment
  DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
  SECRET_KEY: e8c66
  PORT: 8001
  EMAIL_URL: smtp://smtp.gmail.com
  DEFAULT_FROM_EMAIL: thedata.collect@gmail.com # thedata.collect@gmail.com:qwazer123
  GLITCHTIP_DOMAIN: "https://glitchtip-web.org"
  ENABLE_OPEN_USER_REGISTRATION: "True"
  GLITCHTIP_MAX_EVENT_LIFE_DAYS: 30
  CELERY_WORKER_CONCURRENCY: 2 # Set to 2 to prevent excessive memory usage. Change it or remove to set it to the number of cpu cores.
x-depends_on:
  &default-depends_on
  - postgres
  - redis


networks:
  eurygaster:
    external: true

services:

  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - eurygaster

  redis:
    image: redis
    restart: unless-stopped
    networks:
      - eurygaster
    volumes:
      - redis:/data

  gtweb:
    image: glitchtip/glitchtip:v3.1.3
    depends_on: *default-depends_on
    ports:
      - "8001:8001"
    environment: *default-environment
    restart: unless-stopped
    volumes:
      - uploads:/code/uploads
    networks:
      eurygaster:
        ipv4_address: 172.55.0.6

  gtworker:
    image: glitchtip/glitchtip:v3.1.3
    command: ./bin/run-celery-with-beat.sh
    depends_on: *default-depends_on
    environment: *default-environment
    restart: unless-stopped
    volumes:
      - uploads:/code/uploads
    networks:
      - eurygaster

  migrate:
    image: glitchtip/glitchtip:v3.1.3
    depends_on: *default-depends_on
    command: "./manage.py migrate"
    environment: *default-environment
    networks:
      - eurygaster

volumes:
  pg-data:
  uploads:
  redis:
