name: Build Docker (Windows 2019) image and publish to DockerHub

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Application version'
        required: true

jobs:
  build:
    runs-on: 'windows-2019'
    steps:
      - uses: actions/checkout@v2

      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        env:
            DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
            APP_VERSION: ${{ github.event.inputs.version }}
        run: docker build -f ./dockerfiles/wincoreserver1809.Dockerfile -t $env:DOCKER_USER/eurygaster_app:latest_windowsservercore_1809 -t $env:DOCKER_USER/eurygaster_app:$env:APP_VERSION"_windowsservercore_1809" .

      - name: Push docker image
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          APP_VERSION: ${{ github.event.inputs.version }}
        run: |
          docker push $env:DOCKER_USER/eurygaster_app:latest_windowsservercore_1809
          docker push $env:DOCKER_USER/eurygaster_app:$env:APP_VERSION"_windowsservercore_1809"
          
